[tool.black]
line-length = 79
target_version = ['py36']
skip-string-normalization = 1
# Needed for the vim plugin
string-normalization = 0
exclude = '''
(
    /(
          \.eggs
        | \.git
        | .tox
        | \.venv
        | dist
        | build
        | _build
        | db-testtools-venv
    )/
)
'''

[tool.coverage.run]
omit = [
    '*dbtesttools/tests*',
    '*dbtesttools/testing*',
    'dbtesttools/__init__.py',
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["I", "S"]
