[tool.coverage.run]
omit = [
    '*dbtesttools/tests*',
    '*dbtesttools/testing*',
    'dbtesttools/__init__.py',
]

[tool.ruff]
line-length = 79
output-format = "full"
target-version = 'py37'
exclude = [
    ".git",
    ".tox",
    "__pycache__",
    "alembic",
    "bin",
    "lib",
    "build",
    "dist",
    ".eggs",
]

[tool.ruff.format]
quote-style = 'preserve'

[tool.ruff.lint]
select = ["B", "C9", "D", "E", "F", "I", "S", "W"]
ignore = [
    "D10",  # ignore missing docstrings (for now)
    "D203", # Allow One Blank Line Before Class
    "D213", # Allow "Multi-line docstring summary should start at the second line"
]
mccabe.max-complexity = 13
